// <auto-generated />
using System;
using HRMatrix.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRMatrix.Persistence.Migrations
{
    [DbContext(typeof(HRMatrixDbContext))]
    [Migration("20240930142318_Added_WOrk_Experience")]
    partial class Added_WOrk_Experience
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRMatrix.Domain.Entities.EducationLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EducationLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Высшее законченное (Магистр)"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Среднее специальное / профессиональное"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Кандидат наук"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Доктор наук"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Доцент"
                        });
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.EducationLevelTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EducationLevelId")
                        .HasColumnType("int");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("EducationLevelId");

                    b.ToTable("EducationLevelTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EducationLevelId = 1,
                            LanguageCode = "ru-RU",
                            Name = "Высшее законченное (Магистр)"
                        },
                        new
                        {
                            Id = 2,
                            EducationLevelId = 1,
                            LanguageCode = "en-US",
                            Name = "Higher Education (Master)"
                        },
                        new
                        {
                            Id = 3,
                            EducationLevelId = 1,
                            LanguageCode = "ky-KG",
                            Name = "Жогорку билим (Магистр)"
                        },
                        new
                        {
                            Id = 4,
                            EducationLevelId = 2,
                            LanguageCode = "ru-RU",
                            Name = "Среднее специальное / профессиональное"
                        },
                        new
                        {
                            Id = 5,
                            EducationLevelId = 2,
                            LanguageCode = "en-US",
                            Name = "Specialized Secondary / Professional"
                        },
                        new
                        {
                            Id = 6,
                            EducationLevelId = 2,
                            LanguageCode = "ky-KG",
                            Name = "Орточо кесиптик билим"
                        },
                        new
                        {
                            Id = 7,
                            EducationLevelId = 3,
                            LanguageCode = "ru-RU",
                            Name = "Кандидат наук"
                        },
                        new
                        {
                            Id = 8,
                            EducationLevelId = 3,
                            LanguageCode = "en-US",
                            Name = "Candidate of Sciences"
                        },
                        new
                        {
                            Id = 9,
                            EducationLevelId = 3,
                            LanguageCode = "ky-KG",
                            Name = "Илим кандидаты"
                        },
                        new
                        {
                            Id = 10,
                            EducationLevelId = 4,
                            LanguageCode = "ru-RU",
                            Name = "Доктор наук"
                        },
                        new
                        {
                            Id = 11,
                            EducationLevelId = 4,
                            LanguageCode = "en-US",
                            Name = "Doctor of Sciences"
                        },
                        new
                        {
                            Id = 12,
                            EducationLevelId = 4,
                            LanguageCode = "ky-KG",
                            Name = "Илим доктору"
                        },
                        new
                        {
                            Id = 13,
                            EducationLevelId = 5,
                            LanguageCode = "ru-RU",
                            Name = "Доцент"
                        },
                        new
                        {
                            Id = 14,
                            EducationLevelId = 5,
                            LanguageCode = "en-US",
                            Name = "Associate Professor"
                        },
                        new
                        {
                            Id = 15,
                            EducationLevelId = 5,
                            LanguageCode = "ky-KG",
                            Name = "Ассистент профессор"
                        });
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.UserEducation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EducationLevelId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EducationLevelId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("UserEducations");
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.WorkExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Achievements")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("WorkExperience");
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = 2,
                            Name = "SuperUser",
                            NormalizedName = "SUPERUSER"
                        },
                        new
                        {
                            Id = 3,
                            Name = "HR",
                            NormalizedName = "HR"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cfcde115-ea04-4f1d-832d-c8b17cc43810",
                            Email = "user@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@MAIL.COM",
                            NormalizedUserName = "USER",
                            PasswordHash = "AQAAAAIAAYagAAAAEN2tmwARrXhqFXYXMluBZWbr1cUgIIOQwVkJHckzsFfZayyL8N3Kspre6gxwwCsMvA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "91a8099b-649d-40eb-a782-3b6c759902af",
                            TwoFactorEnabled = false,
                            UserName = "user"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bcc24f7c-c378-47e0-bd58-338bb988e4c1",
                            Email = "superuser@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERUSER@MAIL.COM",
                            NormalizedUserName = "SUPERUSER",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ9O61uWrO/m4Ma9rjTM1sYFQfmnOJbw9O4gCmo1zb4vleLWehdnxgxQ/fi4XrEIeQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "62857d07-9441-4d5d-b2a1-b7652a922dbf",
                            TwoFactorEnabled = false,
                            UserName = "superuser"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "27e7cd76-301e-46ad-a465-af490a2c8554",
                            Email = "hr@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "HR@MAIL.COM",
                            NormalizedUserName = "HR",
                            PasswordHash = "AQAAAAIAAYagAAAAEOm+A2xc9fuAoI8mF17G96TIE9D+2JrjpdgSKKpBKkeBW7+HnjSVg24KhZ6+HeJ7Iw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fb04ead6-e90c-4a3a-ba47-7d3e2d20d768",
                            TwoFactorEnabled = false,
                            UserName = "hr"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "315beb1e-0f58-4d59-8f2c-1b985259b529",
                            Email = "admin@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@MAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEGOVG/h8XSogXn/lIc3Vgx5y/lZETNN2G+m3vjwgtCg5t6nwQtEIhkOirmE2RxjC3A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b4fddf10-8ab6-4257-af3b-9ff589fad499",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationUserToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.EducationLevelTranslation", b =>
                {
                    b.HasOne("HRMatrix.Domain.Entities.EducationLevel", "EducationLevel")
                        .WithMany("Translations")
                        .HasForeignKey("EducationLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationLevel");
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.UserEducation", b =>
                {
                    b.HasOne("HRMatrix.Domain.Entities.EducationLevel", "EducationLevel")
                        .WithMany()
                        .HasForeignKey("EducationLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMatrix.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("UserEducations")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationLevel");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.WorkExperience", b =>
                {
                    b.HasOne("HRMatrix.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("WorkExperiences")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationRoleClaim", b =>
                {
                    b.HasOne("HRMatrix.IdentityService.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationUserClaim", b =>
                {
                    b.HasOne("HRMatrix.IdentityService.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationUserLogin", b =>
                {
                    b.HasOne("HRMatrix.IdentityService.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationUserRole", b =>
                {
                    b.HasOne("HRMatrix.IdentityService.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMatrix.IdentityService.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationUserToken", b =>
                {
                    b.HasOne("HRMatrix.IdentityService.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.EducationLevel", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.UserProfile", b =>
                {
                    b.Navigation("UserEducations");

                    b.Navigation("WorkExperiences");
                });
#pragma warning restore 612, 618
        }
    }
}
