// <auto-generated />
using System;
using HRMatrix.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRMatrix.Persistence.Migrations
{
    [DbContext(typeof(HRMatrixDbContext))]
    [Migration("20240930145657_AdditionalSkills")]
    partial class AdditionalSkills
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRMatrix.Domain.Entities.EducationLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EducationLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Высшее законченное (Магистр)"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Среднее специальное / профессиональное"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Кандидат наук"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Доктор наук"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Доцент"
                        });
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.EducationLevelTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EducationLevelId")
                        .HasColumnType("int");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("EducationLevelId");

                    b.ToTable("EducationLevelTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EducationLevelId = 1,
                            LanguageCode = "ru-RU",
                            Name = "Высшее законченное (Магистр)"
                        },
                        new
                        {
                            Id = 2,
                            EducationLevelId = 1,
                            LanguageCode = "en-US",
                            Name = "Higher Education (Master)"
                        },
                        new
                        {
                            Id = 3,
                            EducationLevelId = 1,
                            LanguageCode = "ky-KG",
                            Name = "Жогорку билим (Магистр)"
                        },
                        new
                        {
                            Id = 4,
                            EducationLevelId = 2,
                            LanguageCode = "ru-RU",
                            Name = "Среднее специальное / профессиональное"
                        },
                        new
                        {
                            Id = 5,
                            EducationLevelId = 2,
                            LanguageCode = "en-US",
                            Name = "Specialized Secondary / Professional"
                        },
                        new
                        {
                            Id = 6,
                            EducationLevelId = 2,
                            LanguageCode = "ky-KG",
                            Name = "Орточо кесиптик билим"
                        },
                        new
                        {
                            Id = 7,
                            EducationLevelId = 3,
                            LanguageCode = "ru-RU",
                            Name = "Кандидат наук"
                        },
                        new
                        {
                            Id = 8,
                            EducationLevelId = 3,
                            LanguageCode = "en-US",
                            Name = "Candidate of Sciences"
                        },
                        new
                        {
                            Id = 9,
                            EducationLevelId = 3,
                            LanguageCode = "ky-KG",
                            Name = "Илим кандидаты"
                        },
                        new
                        {
                            Id = 10,
                            EducationLevelId = 4,
                            LanguageCode = "ru-RU",
                            Name = "Доктор наук"
                        },
                        new
                        {
                            Id = 11,
                            EducationLevelId = 4,
                            LanguageCode = "en-US",
                            Name = "Doctor of Sciences"
                        },
                        new
                        {
                            Id = 12,
                            EducationLevelId = 4,
                            LanguageCode = "ky-KG",
                            Name = "Илим доктору"
                        },
                        new
                        {
                            Id = 13,
                            EducationLevelId = 5,
                            LanguageCode = "ru-RU",
                            Name = "Доцент"
                        },
                        new
                        {
                            Id = 14,
                            EducationLevelId = 5,
                            LanguageCode = "en-US",
                            Name = "Associate Professor"
                        },
                        new
                        {
                            Id = 15,
                            EducationLevelId = 5,
                            LanguageCode = "ky-KG",
                            Name = "Ассистент профессор"
                        });
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.FamilyStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaritalStatusId")
                        .HasColumnType("int");

                    b.Property<string>("MarriagePeriods")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("NumberOfChildren")
                        .HasColumnType("int");

                    b.Property<int>("TimesMarried")
                        .HasColumnType("int");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaritalStatusId");

                    b.HasIndex("UserProfileId")
                        .IsUnique();

                    b.ToTable("FamilyStatuses");
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Английский"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Турецкий"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Немецкий"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Китайский"
                        });
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.LanguageTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("LanguageTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LanguageCode = "en-US",
                            LanguageId = 1,
                            Name = "English"
                        },
                        new
                        {
                            Id = 2,
                            LanguageCode = "ru-RU",
                            LanguageId = 1,
                            Name = "Английский"
                        },
                        new
                        {
                            Id = 3,
                            LanguageCode = "en-US",
                            LanguageId = 2,
                            Name = "Turkish"
                        },
                        new
                        {
                            Id = 4,
                            LanguageCode = "ru-RU",
                            LanguageId = 2,
                            Name = "Турецкий"
                        },
                        new
                        {
                            Id = 5,
                            LanguageCode = "en-US",
                            LanguageId = 3,
                            Name = "German"
                        },
                        new
                        {
                            Id = 6,
                            LanguageCode = "ru-RU",
                            LanguageId = 3,
                            Name = "Немецкий"
                        },
                        new
                        {
                            Id = 7,
                            LanguageCode = "en-US",
                            LanguageId = 4,
                            Name = "Chinese"
                        },
                        new
                        {
                            Id = 8,
                            LanguageCode = "ru-RU",
                            LanguageId = 4,
                            Name = "Китайский"
                        });
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.MaritalStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("MaritalStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Женат/Замужем"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Холост/Не замужем"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Разведен(а)"
                        });
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.MaritalStatusTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("MaritalStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("MaritalStatusId");

                    b.ToTable("MaritalStatusTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LanguageCode = "en-US",
                            MaritalStatusId = 1,
                            Name = "Married"
                        },
                        new
                        {
                            Id = 2,
                            LanguageCode = "ky-KG",
                            MaritalStatusId = 1,
                            Name = "Күйөөм (Замужем)"
                        },
                        new
                        {
                            Id = 3,
                            LanguageCode = "en-US",
                            MaritalStatusId = 2,
                            Name = "Single"
                        },
                        new
                        {
                            Id = 4,
                            LanguageCode = "ky-KG",
                            MaritalStatusId = 2,
                            Name = "Бекар"
                        },
                        new
                        {
                            Id = 5,
                            LanguageCode = "en-US",
                            MaritalStatusId = 3,
                            Name = "Divorced"
                        },
                        new
                        {
                            Id = 6,
                            LanguageCode = "ky-KG",
                            MaritalStatusId = 3,
                            Name = "Ажыратылган"
                        });
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.UserEducation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EducationLevelId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EducationLevelId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("UserEducations");
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalCompetences")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("AdditionalSkills")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaritalStatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaritalStatusId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.WorkExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Achievements")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("WorkExperiences");
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = 2,
                            Name = "SuperUser",
                            NormalizedName = "SUPERUSER"
                        },
                        new
                        {
                            Id = 3,
                            Name = "HR",
                            NormalizedName = "HR"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ae2c6bab-f702-4ef8-a2b1-f69cd4a70ebe",
                            Email = "user@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@MAIL.COM",
                            NormalizedUserName = "USER",
                            PasswordHash = "AQAAAAIAAYagAAAAEECI7+wX3C8w3NvcM6YO9gVqgshMRMOxxCZw1lX9XJTcoaAhz5pgwacQk7UN709O2A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "21191e95-9a28-4cc6-a437-b540cd13a611",
                            TwoFactorEnabled = false,
                            UserName = "user"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "81bca07b-bc7b-4fe3-8405-48ba989c7204",
                            Email = "superuser@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERUSER@MAIL.COM",
                            NormalizedUserName = "SUPERUSER",
                            PasswordHash = "AQAAAAIAAYagAAAAEKVCyF2r9cQNald5WrIq6kBi1VZ8fT1CpgFFpAHQisHf5ZuNCq5CAOdCDw6TCNS7RQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7853fc68-2cb9-4d3a-969f-e2a1429f17ab",
                            TwoFactorEnabled = false,
                            UserName = "superuser"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c1d24371-15ac-43d1-a652-ca3bf5d85646",
                            Email = "hr@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "HR@MAIL.COM",
                            NormalizedUserName = "HR",
                            PasswordHash = "AQAAAAIAAYagAAAAEOLgkOYxWDfRkkbdM/yAhBch7WZcjQogugKVRW5Ugi6hBKOKZ5UGNTpnYISio1TXkw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "62be930e-c28c-4faf-bde5-2060721ba3ff",
                            TwoFactorEnabled = false,
                            UserName = "hr"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7c46de2e-666d-4c8d-8e0c-3b63285b884e",
                            Email = "admin@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@MAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAECfkqBOajwe7ZjhkupNk4cbGvNBprkIOknOgaWe7GJhi5nuTvZOnJsHcOXUFi7NhsQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "980c3233-3321-454c-a85d-06e404cf1abe",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationUserToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.EducationLevelTranslation", b =>
                {
                    b.HasOne("HRMatrix.Domain.Entities.EducationLevel", "EducationLevel")
                        .WithMany("Translations")
                        .HasForeignKey("EducationLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationLevel");
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.FamilyStatus", b =>
                {
                    b.HasOne("HRMatrix.Domain.Entities.MaritalStatus", "MaritalStatus")
                        .WithMany()
                        .HasForeignKey("MaritalStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMatrix.Domain.Entities.UserProfile", "UserProfile")
                        .WithOne("FamilyStatus")
                        .HasForeignKey("HRMatrix.Domain.Entities.FamilyStatus", "UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaritalStatus");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.Language", b =>
                {
                    b.HasOne("HRMatrix.Domain.Entities.UserProfile", null)
                        .WithMany("UserLanguages")
                        .HasForeignKey("UserProfileId");
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.LanguageTranslation", b =>
                {
                    b.HasOne("HRMatrix.Domain.Entities.Language", "Language")
                        .WithMany("Translations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.MaritalStatusTranslation", b =>
                {
                    b.HasOne("HRMatrix.Domain.Entities.MaritalStatus", "MaritalStatus")
                        .WithMany()
                        .HasForeignKey("MaritalStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaritalStatus");
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.UserEducation", b =>
                {
                    b.HasOne("HRMatrix.Domain.Entities.EducationLevel", "EducationLevel")
                        .WithMany()
                        .HasForeignKey("EducationLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMatrix.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("UserEducations")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationLevel");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("HRMatrix.Domain.Entities.MaritalStatus", null)
                        .WithMany("UserProfiles")
                        .HasForeignKey("MaritalStatusId");
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.WorkExperience", b =>
                {
                    b.HasOne("HRMatrix.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("WorkExperiences")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationRoleClaim", b =>
                {
                    b.HasOne("HRMatrix.IdentityService.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationUserClaim", b =>
                {
                    b.HasOne("HRMatrix.IdentityService.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationUserLogin", b =>
                {
                    b.HasOne("HRMatrix.IdentityService.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationUserRole", b =>
                {
                    b.HasOne("HRMatrix.IdentityService.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMatrix.IdentityService.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationUserToken", b =>
                {
                    b.HasOne("HRMatrix.IdentityService.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.EducationLevel", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.Language", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.MaritalStatus", b =>
                {
                    b.Navigation("UserProfiles");
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.UserProfile", b =>
                {
                    b.Navigation("FamilyStatus")
                        .IsRequired();

                    b.Navigation("UserEducations");

                    b.Navigation("UserLanguages");

                    b.Navigation("WorkExperiences");
                });
#pragma warning restore 612, 618
        }
    }
}
