// <auto-generated />
using System;
using HRMatrix.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRMatrix.Persistence.Migrations
{
    [DbContext(typeof(HRMatrixDbContext))]
    [Migration("20240930140137_AddedUserProfile")]
    partial class AddedUserProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRMatrix.Domain.Entities.EducationLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EducationLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Высшее законченное (Магистр)"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Среднее специальное / профессиональное"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Кандидат наук"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Доктор наук"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Доцент"
                        });
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.EducationLevelTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EducationLevelId")
                        .HasColumnType("int");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("EducationLevelId");

                    b.ToTable("EducationLevelTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EducationLevelId = 1,
                            LanguageCode = "ru-RU",
                            Name = "Высшее законченное (Магистр)"
                        },
                        new
                        {
                            Id = 2,
                            EducationLevelId = 1,
                            LanguageCode = "en-US",
                            Name = "Higher Education (Master)"
                        },
                        new
                        {
                            Id = 3,
                            EducationLevelId = 1,
                            LanguageCode = "ky-KG",
                            Name = "Жогорку билим (Магистр)"
                        },
                        new
                        {
                            Id = 4,
                            EducationLevelId = 2,
                            LanguageCode = "ru-RU",
                            Name = "Среднее специальное / профессиональное"
                        },
                        new
                        {
                            Id = 5,
                            EducationLevelId = 2,
                            LanguageCode = "en-US",
                            Name = "Specialized Secondary / Professional"
                        },
                        new
                        {
                            Id = 6,
                            EducationLevelId = 2,
                            LanguageCode = "ky-KG",
                            Name = "Орточо кесиптик билим"
                        },
                        new
                        {
                            Id = 7,
                            EducationLevelId = 3,
                            LanguageCode = "ru-RU",
                            Name = "Кандидат наук"
                        },
                        new
                        {
                            Id = 8,
                            EducationLevelId = 3,
                            LanguageCode = "en-US",
                            Name = "Candidate of Sciences"
                        },
                        new
                        {
                            Id = 9,
                            EducationLevelId = 3,
                            LanguageCode = "ky-KG",
                            Name = "Илим кандидаты"
                        },
                        new
                        {
                            Id = 10,
                            EducationLevelId = 4,
                            LanguageCode = "ru-RU",
                            Name = "Доктор наук"
                        },
                        new
                        {
                            Id = 11,
                            EducationLevelId = 4,
                            LanguageCode = "en-US",
                            Name = "Doctor of Sciences"
                        },
                        new
                        {
                            Id = 12,
                            EducationLevelId = 4,
                            LanguageCode = "ky-KG",
                            Name = "Илим доктору"
                        },
                        new
                        {
                            Id = 13,
                            EducationLevelId = 5,
                            LanguageCode = "ru-RU",
                            Name = "Доцент"
                        },
                        new
                        {
                            Id = 14,
                            EducationLevelId = 5,
                            LanguageCode = "en-US",
                            Name = "Associate Professor"
                        },
                        new
                        {
                            Id = 15,
                            EducationLevelId = 5,
                            LanguageCode = "ky-KG",
                            Name = "Ассистент профессор"
                        });
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.UserEducation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EducationLevelId")
                        .HasColumnType("int");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EducationLevelId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("UserEducations");
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = 2,
                            Name = "SuperUser",
                            NormalizedName = "SUPERUSER"
                        },
                        new
                        {
                            Id = 3,
                            Name = "HR",
                            NormalizedName = "HR"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "19c853bd-b554-4cb1-8a70-e6d52ec559fc",
                            Email = "user@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@MAIL.COM",
                            NormalizedUserName = "USER",
                            PasswordHash = "AQAAAAIAAYagAAAAEIyE161R5YTyxw1pyC5DKQ+XrqFVvOSgW4/P4272xpB7UGnhe1IXe9ipEP2c1VMt6Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3e0fc776-fc33-4395-b65d-a3f13332e801",
                            TwoFactorEnabled = false,
                            UserName = "user"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "287ed7cd-42ac-4db0-8a44-d46d6e8bde89",
                            Email = "superuser@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERUSER@MAIL.COM",
                            NormalizedUserName = "SUPERUSER",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ1cs3Lxz1FXaoMbR2uRyIhxfI8/uSPSVWvbGI+OoBZ7Y0bFvMGlfdwqOJb38hoeZw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4356a635-ed0a-4383-9d9e-c1d62136fe51",
                            TwoFactorEnabled = false,
                            UserName = "superuser"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "13b59d7e-5400-4b8c-af84-d47d269d6dcf",
                            Email = "hr@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "HR@MAIL.COM",
                            NormalizedUserName = "HR",
                            PasswordHash = "AQAAAAIAAYagAAAAEJe0pIGhiGy/cyRw0wZUmLVVwRbQaV+f8yOAv/VZhBP4PBwl5uhSXJfeDHKrtb4cDw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d0014b30-de17-41b5-8bea-71259594f749",
                            TwoFactorEnabled = false,
                            UserName = "hr"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bfefe5b8-57a0-43be-8f49-5bc82219054a",
                            Email = "admin@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@MAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEBkvGEkqmnaQpZHg2XPX3KziJwhaPmdXWQGYY1hOzqWy7wium7YDbMgjnkzVoUP90Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5513ad60-4c36-49db-bff2-7c0dc245de14",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationUserToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.EducationLevelTranslation", b =>
                {
                    b.HasOne("HRMatrix.Domain.Entities.EducationLevel", "EducationLevel")
                        .WithMany("Translations")
                        .HasForeignKey("EducationLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationLevel");
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.UserEducation", b =>
                {
                    b.HasOne("HRMatrix.Domain.Entities.EducationLevel", "EducationLevel")
                        .WithMany()
                        .HasForeignKey("EducationLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMatrix.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("UserEducations")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationLevel");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationRoleClaim", b =>
                {
                    b.HasOne("HRMatrix.IdentityService.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationUserClaim", b =>
                {
                    b.HasOne("HRMatrix.IdentityService.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationUserLogin", b =>
                {
                    b.HasOne("HRMatrix.IdentityService.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationUserRole", b =>
                {
                    b.HasOne("HRMatrix.IdentityService.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMatrix.IdentityService.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMatrix.IdentityService.Models.ApplicationUserToken", b =>
                {
                    b.HasOne("HRMatrix.IdentityService.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.EducationLevel", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("HRMatrix.Domain.Entities.UserProfile", b =>
                {
                    b.Navigation("UserEducations");
                });
#pragma warning restore 612, 618
        }
    }
}
